
db.restaurants.find( {} );
db.restaurants.find( {}, { projection: { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 } } );
db.restaurants.find( {}, { projection: { restaurant_id: 1, name: 1, borough: 1, address: { zipcode: 1 }, cuisine: 1, _id: 0 } } );
db.restaurants.find( { borough: 'Bronx' } );
db.restaurants.find( { borough: 'Bronx' } ).limit( 5 );
db.restaurants.find( { borough: 'Bronx' } ).skip( 5 ).limit( 5 );
db.restaurants.find( { grades: { $elemMatch: { score: { $gt: 90 } } } } );
db.restaurants.find( { grades: { $elemMatch: { score: { $gt: 80, $lt: 100 } } } } );
db.restaurants.find( { 'address.coord': { $lt: -95.754168 } } );
db.restaurants.find( { cuisine: { $ne: 'American ' }, grades: { $elemMatch: { score: { $gt: 70 } } }, 'address.coord': { $lt: -65.754168 } } );
db.restaurants.find( { cuisine: { $ne: 'American ' }, grades: { $elemMatch: { score: { $gt: 70 } } }, 'address.coord': { $lt: -65.754168 } } );
db.restaurants.find( { cuisine: { $ne: 'American ' }, grades: { $elemMatch: { grade: 'A' } }, borough: { $ne: 'Brooklyn' } } ).sort( { cuisine: -1 } );
db.restaurants.find( { name: { $regex: /^Wil/ } }, { projection: { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 } } );
db.restaurants.find( { name: { $regex: /ces$/ } }, { projection: { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 } } );
db.restaurants.find( { name: { $regex: /Reg/ } }, { projection: { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 } } );
db.restaurants.find( { borough: 'Bronx', $or: [ { cuisine: 'American ' }, { cuisine: 'Chinese' } ] } );
db.restaurants.find( { borough: { $in: [ 'Staten Island', 'Queens', 'Bronx', 'Brooklyn' ] } }, { projection: { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 } } );
db.restaurants.find( { borough: { $nin: [ 'Staten Island', 'Queens', 'Bronx', 'Brooklyn' ] } }, { projection: { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 } } );
db.restaurants.find( { grades: { $elemMatch: { score: { $lt: 10 } } } }, { projection: { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 } } );
db.restaurants.find( { cuisine: 'Seafood', $nor: [ { cuisine: 'American ' }, { cuisine: 'Chinese' }, { name: { $regex: /^Wil/ } } ] }, { projection: { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 } } );
db.restaurants.find( { grades: { $elemMatch: { grade: 'A', score: 11, date: new Date( '2014-08-11T00:00:00Z' ) } } }, { projection: { restaurant_id: 1, name: 1, grades: 1 } } );
db.restaurants.find( { grades: { $elemMatch: { grade: 'A', score: 9, date: new Date( '2014-08-11T00:00:00Z' ) } } }, { projection: { restaurant_id: 1, name: 1, grades: 1 } } );
db.restaurants.find( { 'address.coord': { $elemMatch: { $gt: 42, $lt: 52 } } }, { projection: { restaurant_id: 1, name: 1, address: 1 } } );
db.restaurants.find().sort( { name: 1 } );
db.restaurants.find().sort( { name: -1 } );
db.restaurants.find().sort( { cuisine: 1, borough: -1 } );
db.restaurants.find( { 'address.street': { $exists: true } } );
db.restaurants.find( { 'address.coord': { $type: 'double' } } );
db.restaurants.find( { grades: { $elemMatch: { score: { $mod: [ 7, 0 ] } } } }, { projection: { restaurant_id: 1, name: 1, grades: 1 } } );
db.restaurants.find( { name: { $regex: /mon/ } }, { projection: { name: 1, borough: 1, 'address.coord': 1, cuisine: 1 } } );
db.restaurants.find( { name: { $regex: /^Mad/ } }, { projection: { name: 1, borough: 1, 'address.coord': 1, cuisine: 1 } } );
